<a href="https://colab.research.google.com/github/DanielYaari28/AIPI510P1/blob/daniel-eda/notebooks/college_scorecard_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import zipfile

zip_path = "/content/College_Scorecard_Raw_Data_06102026.zip"

file_name = (
    "College_Scorecard_Raw_Data_06032026/"
    "Most-Recent-Cohorts-Institution.csv"
)

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open(file_name) as f:
        df = pd.read_csv(f, low_memory=False)

df.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,MD_EARN_WNE_INC1_P11,MD_EARN_WNE_INC2_P11,MD_EARN_WNE_INC3_P11,MD_EARN_WNE_INDEP0_P11,MD_EARN_WNE_INDEP1_P11,MD_EARN_WNE_MALE0_P11,MD_EARN_WNE_MALE1_P11,SCORECARD_SECTOR,EARN_THR_STATE,EARN_THR_NAT
0,100654,100200.0,1002.0,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,36650.0,41070.0,47016.0,38892.0,41738.0,38167.0,40250.0,4,32204.0,36082.0
1,100663,105200.0,1052.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu/,https://tcc.ruffalonl.com/University of Alabam...,...,47182.0,51896.0,54368.0,50488.0,51505.0,46559.0,59181.0,4,32204.0,36082.0
2,100690,2503400.0,25034.0,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,https://www.amridgeuniversity.edu/,https://www2.amridgeuniversity.edu:9091/,...,35752.0,41007.0,NaN,NaN,38467.0,32654.0,49435.0,5,32204.0,36082.0
3,100706,105500.0,1055.0,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu/,uah.clearcostcalculator.com/student/default/ne...,...,51208.0,62219.0,62577.0,55920.0,60221.0,47787.0,67454.0,4,32204.0,36082.0
4,100724,100500.0,1005.0,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu/,tcc.ruffalonl.com/Alabama State University/Fre...,...,32844.0,36932.0,37966.0,34294.0,31797.0,32303.0,36964.0,4,32204.0,36082.0

In [6]:
df[[
    "INSTNM",
    "STABBR",
    "CONTROL",
    "ADM_RATE",
    "COSTT4_A",
    "DEBT_MDN",
    "MD_EARN_WNE_P10"
]].head(10)

,INSTNM,STABBR,CONTROL,ADM_RATE,COSTT4_A,DEBT_MDN,MD_EARN_WNE_P10
0,Alabama A & M University,AL,1,0.5795,27153.0,16600,40628.0
1,University of Alabama at Birmingham,AL,1,0.8818,28145.0,15832,54501.0
2,Amridge University,AL,2,NaN,NaN,13385,37621.0
3,University of Alabama in Huntsville,AL,1,0.6857,27392.0,13905,61767.0
4,Alabama State University,AL,1,0.9755,23586.0,17500,34502.0
5,The University of Alabama,AL,1,0.7665,33382.0,17986,59221.0
6,Central Alabama Community College,AL,1,NaN,21413.0,5500,33506.0
7,Athens State University,AL,1,NaN,NaN,14861,50273.0
8,Auburn University at Montgomery,AL,1,0.9157,21353.0,13119,44391.0
9,Auburn University,AL,1,0.4592,34919.0,17750,65337.0

In [7]:
student_success = df[
    ["INSTNM", "C150_4", "RET_FT4"]
].copy()

student_success.head(10)

                                INSTNM  C150_4  RET_FT4
0             Alabama A & M University  0.2403   0.6989
1  University of Alabama at Birmingham  0.6423   0.8009
2                   Amridge University  1.0000      NaN
3  University of Alabama in Huntsville  0.6429   0.8425
4             Alabama State University  0.3034   0.6975
5            The University of Alabama  0.7337   0.8949
6    Central Alabama Community College     NaN      NaN
7              Athens State University     NaN      NaN
8      Auburn University at Montgomery  0.3260   0.6757
9                    Auburn University  0.8195   0.9478

In [13]:
eligible = df[
    (df["PREDDEG"] == 3) &   # Primarily bachelor's-degree granting
    (df["UGDS"] >= 2000)     # At least 2,000 undergraduates
].copy()

print("Eligible universities:", len(eligible))

Eligible universities: 828

In [14]:
eligible[
    ["INSTNM", "UGDS", "PREDDEG", "CONTROL"]
].sort_values("UGDS", ascending=False).head(20)

                                          INSTNM      UGDS  PREDDEG  CONTROL
1796           Southern New Hampshire University  163164.0        3        2
4026                Western Governors University  155088.0        3        2
5092               University of Phoenix-Arizona   85991.0        3        3
80                       Grand Canyon University   73371.0        3        2
68     Arizona State University Campus Immersion   64674.0        3        1
3113        Texas A&M University-College Station   59615.0        3        1
583                University of Central Florida   59146.0        3        1
5030  Arizona State University Digital Immersion   53782.0        3        1
3207                          Liberty University   50012.0        3        2
1301        University of Maryland Global Campus   49664.0        3        1
2439           Ohio State University-Main Campus   45638.0        3        1
3494               Purdue University-Main Campus   44503.0        3        1
3115           The University of Texas at Austin   42855.0        3        1
70                         University of Arizona   42537.0        3        1
2713   Pennsylvania State University-Main Campus   42284.0        3        1
5170                   Kennesaw State University   41254.0        3        1
1491                   Michigan State University   40922.0        3        1
4370           American Public University System   40074.0        3        3
603             Florida International University   39508.0        3        1
196        California State University-Fullerton   38546.0        3        1

In [15]:
eligible[
    ["INSTNM", "UGDS"]
].sort_values("UGDS").head(20)

                                           INSTNM    UGDS
2814                         Bob Jones University  2005.0
2099                    St Bonaventure University  2012.0
477                              Colorado College  2014.0
169                  Art Center College of Design  2017.0
1001                            Taylor University  2025.0
1918                Western New Mexico University  2026.0
2010                             Hamilton College  2030.0
3140                   Wayland Baptist University  2041.0
2409                    Miami University-Hamilton  2043.0
2157                                Union College  2046.0
386                        University of Redlands  2049.0
509      Rocky Mountain College of Art and Design  2050.0
2470                            Tiffin University  2051.0
2846        University of South Carolina Beaufort  2052.0
2307                       Minot State University  2062.0
3476           University of Puerto Rico at Cayey  2069.0
2869                      Dakota State University  2071.0
2879  South Dakota School of Mines and Technology  2071.0
1430                             Williams College  2076.0
1003                        Valparaiso University  2083.0

In [17]:
eda_cols = [
    # Identification
    "UNITID",
    "INSTNM",
    "UGDS",
    "PREDDEG",
    "CONTROL",

    # Student Success
    "C150_4",
    "RET_FT4",

    # Affordability
    "NPT4_PUB",
    "NPT4_PRIV",
    "DEBT_MDN",

    # Outcomes
    "MD_EARN_WNE_P10",

    # Accessibility
    "PCTPELL"
]

eda = eligible[eda_cols].copy()

In [18]:
eda.info()

<class 'pandas.core.frame.DataFrame'>
Index: 828 entries, 0 to 5640
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UNITID           828 non-null    int64
 1   INSTNM           828 non-null    object
 2   UGDS             828 non-null    float64
 3   PREDDEG          828 non-null    int64
 4   CONTROL          828 non-null    int64
 5   C150_4           820 non-null    float64
 6   RET_FT4          820 non-null    float64
 7   NPT4_PUB         460 non-null    float64
 8   NPT4_PRIV        355 non-null    float64
 9   DEBT_MDN         823 non-null    object
 10  MD_EARN_WNE_P10  820 non-null    float64
 11  PCTPELL          825 non-null    float64
dtypes: float64(7), int64(3), object(2)
memory usage: 84.1+ KB

In [19]:
eda["DEBT_MDN"].value_counts(dropna=False).head(20)

DEBT_MDN
19500    53
15000    39
12500    27
14000    24
17500    21
19000    20
12000    16
11000    15
15750    14
20500    14
13000    14
14250    12
23250    12
18500    12
18750    12
16750    11
15500    11
21500    10
20000    10
16500     9
Name: count, dtype: int64

In [20]:
pd.to_numeric(eda["DEBT_MDN"], errors="coerce").isna().sum()

np.int64(7)